package com.sevogle.link.common.web.client;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Message {
    public enum MessageSource {
        Inbound, Outbound;
    }

    /** GUID Generated by the creator of the message */
    private String _id = "";
    public static final String ID = "_id";

    private String protocalSpecificId;

    private MessageSource messageSource;

    /** java Date.getTime(); */
    private long sent;
    public static final String SENT = "sent";

    private long received;

    private RelatedMessageDescriptor parent;

    private List<String> children = new ArrayList<String>();

    /**
     * 
     */
    private String channelId;

    private AddressDescriptor from;

    private AddressDescriptor replyTo;

    private List<AddressDescriptor> to = new ArrayList<Message.AddressDescriptor>();

    private List<AddressDescriptor> cc = new ArrayList<Message.AddressDescriptor>();

    private List<AddressDescriptor> bcc = new ArrayList<Message.AddressDescriptor>();

    private String subjectNormalized;
    private String subjectRaw;

    private List<NormativeBlockDescriptor> normalizedMessage = new ArrayList<Message.NormativeBlockDescriptor>();

    private List<ContentDescriptor> contentObjects = new ArrayList<Message.ContentDescriptor>();

    public class NormativeBlockDescriptor implements Serializable {
        private static final long serialVersionUID = 1427773323283986046L;
        private String id;
        private long sizeBytes;
        private BlockType type;

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public long getSizeBytes() {
            return sizeBytes;
        }

        public void setSizeBytes(long sizeBytes) {
            this.sizeBytes = sizeBytes;
        }

        public BlockType getType() {
            return type;
        }

        public void setType(BlockType type) {
            this.type = type;
        }

    }

    public enum BlockType {
        BODY, QUOTED, NESTED_QUOTED;
    }

    public class ContentDescriptor implements Serializable {
        private static final long serialVersionUID = -959748997080357708L;
        private String linkContentId;
        private String contentID;
        private String contentType;
        private ContentDisposition disposition;
        private long sizeBytes;

        public String getLinkContentId() {
            return linkContentId;
        }

        public void setLinkContentId(String linkContentId) {
            this.linkContentId = linkContentId;
        }

        public String getContentID() {
            return contentID;
        }

        public void setContentID(String contentID) {
            this.contentID = contentID;
        }

        public String getContentType() {
            return contentType;
        }

        public void setContentType(String contentType) {
            this.contentType = contentType;
        }

        public ContentDisposition getDisposition() {
            return disposition;
        }

        public void setDisposition(ContentDisposition disposition) {
            this.disposition = disposition;
        }

        public long getSizeBytes() {
            return sizeBytes;
        }

        public void setSizeBytes(long sizeBytes) {
            this.sizeBytes = sizeBytes;
        }
    }

    public enum ContentDisposition {
        NONE, EMBEDDED, ATTACHED;
    }

    public class AddressDescriptor implements Serializable {
        private static final long serialVersionUID = 7142344285861383648L;
        private String contactURI;
        private String linkContactId;
        private String personalName;

        public String getContactURI() {
            return contactURI;
        }

        public void setContactURI(String contactURI) {
            this.contactURI = contactURI;
        }

        public String getLinkContactId() {
            return linkContactId;
        }

        public void setLinkContactId(String linkContactId) {
            this.linkContactId = linkContactId;
        }

        public String getPersonalName() {
            return personalName;
        }

        public void setPersonalName(String personalName) {
            this.personalName = personalName;
        }

    }

    public class RelatedMessageDescriptor implements Serializable {
        private static final long serialVersionUID = -4348037062142063351L;
        private String linkMessageId;
        private String protocalSpecificId;

        public String getLinkMessageId() {
            return linkMessageId;
        }

        public void setLinkMessageId(String linkMessageId) {
            this.linkMessageId = linkMessageId;
        }

        public String getProtocalSpecificId() {
            return protocalSpecificId;
        }

        public void setProtocalSpecificId(String protocalSpecificId) {
            this.protocalSpecificId = protocalSpecificId;
        }

    }

    public String getId() {
        return _id;
    }

    public void setId(String id) {
        _id = id;
    }

    public String getProtocalSpecificId() {
        return protocalSpecificId;
    }

    public void setProtocalSpecificId(String protocalSpecificId) {
        this.protocalSpecificId = protocalSpecificId;
    }

    public MessageSource getMessageSource() {
        return messageSource;
    }

    public void setMessageSource(MessageSource messageSource) {
        this.messageSource = messageSource;
    }

    public long getSent() {
        return sent;
    }

    public void setSent(long sent) {
        this.sent = sent;
    }

    public long getReceived() {
        return received;
    }

    public void setReceived(long received) {
        this.received = received;
    }

    public RelatedMessageDescriptor getParent() {
        return parent;
    }

    public void setParent(RelatedMessageDescriptor parent) {
        this.parent = parent;
    }

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }

    public AddressDescriptor getFrom() {
        return from;
    }

    public void setFrom(AddressDescriptor from) {
        this.from = from;
    }

    public AddressDescriptor getReplyTo() {
        return replyTo;
    }

    public void setReplyTo(AddressDescriptor replyTo) {
        this.replyTo = replyTo;
    }

    public String getSubjectNormalized() {
        return subjectNormalized;
    }

    public void setSubjectNormalized(String subjectNormalized) {
        this.subjectNormalized = subjectNormalized;
    }

    public String getSubjectRaw() {
        return subjectRaw;
    }

    public void setSubjectRaw(String subjectRaw) {
        this.subjectRaw = subjectRaw;
    }

    public List<String> getChildren() {
        return children;
    }

    public List<AddressDescriptor> getTo() {
        return to;
    }

    public List<AddressDescriptor> getCc() {
        return cc;
    }

    public List<AddressDescriptor> getBcc() {
        return bcc;
    }

    public List<NormativeBlockDescriptor> getNormalizedMessage() {
        return normalizedMessage;
    }

    public List<ContentDescriptor> getContentObjects() {
        return contentObjects;
    }

}
